FROM eclipse-temurin:21

RUN apt-get update && \
  apt-get install -y curl unzip jq awscli && \
  rm -rf /var/lib/apt/lists/*

# hostのcpu architectureに合わせてsam cliのバイナリをダウンロードしてインストール
# x86_64の場合はaws-sam-cli-linux-x86_64.zipに変更
RUN curl -Lo /tmp/sam.zip \
  https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-arm64.zip && \
  unzip /tmp/sam.zip -d /tmp/sam-installation && \
  /tmp/sam-installation/install && \
  rm -rf /tmp/sam.zip /tmp/sam-installation
